EX(P)
E X (P ^ Q)
E ( not Q ) U ( P v Q )
E ( P v Q ) U ( Q ^ not P )
A (E X ( P ) ) U ( A ( P ) U ( not Q ) )
E X ( Q)
E ( P ) U (not P )
A ( P ) U ( Q )
A F (not P )
A G (not P v (E F ( not Q ) ) )
A X (A F (not ( P v Q ) ) )
A true U not (P)
E F ( P ^ Q )
A G (not P v (E F ( not Q ) ) )
E true U (not P v (E F ( not Q ) ) )